# Generated by Django 5.0.6 on 2024-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('nombre_completo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('elegir_rol', models.CharField(choices=[('Asistente', 'Asistente'), ('Ponente', 'Ponente'), ('Expositor', 'Expositor'), ('Voluntario', 'Voluntario'), ('Organizador', 'Organizador')], max_length=12)),
                ('talleres', models.TextField(blank=True, null=True)),
                ('titulo_presentacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_stand', models.CharField(blank=True, max_length=255, null=True)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=50, null=True)),
                ('funcion_especifica', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
