# Generated by Django 5.0.6 on 2024-09-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_alter_personas_elegir_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='entrada_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
