# Generated by Django 5.0.6 on 2024-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='rol',
            field=models.CharField(choices=[('Asistente', 'Asistente'), ('Ponente', 'Ponente'), ('Expositor', 'Expositor'), ('Voluntario', 'Voluntario'), ('Organizador', 'Organizador')], max_length=20),
        ),
    ]
